### ISSUE TITLE
parametrization for analyzing/visualizing fusion/fission in mammalian genomes 

### ISSUE THREAD

**Issue by lassancejm** [smortezah/smashpp#13]
Hi, 

I would like to visualize the synteny and rearrangements between a few (mammalian) genomes.

While the 'classic' circos-type layout with alignments using mummer works, I think smash/smashpp has benefits and I would like to give it a whirl.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/14118139/164726673-b1a73e73-be9c-4c1d-9635-f616937f1091.png">

Running smashpp with the default settings does not lead to any output. Do you have suggestions regarding which parameters to tweak? The assemblies I am using are chromosome-level ( but short unplaced scaffolds unfiltered). 

Thanks!

**Comment by pratas** [comment]
Hi,

can you provide information about the IDs of two of those sequences?
Also, can you show the parameters used in smashpp?

Best regards,
Diogo

**Comment by lassancejm** [comment]
Hi, 
The two ref are mm10 version Mus musculus genome and version HU_Pman_2.1.3 of P manicualtus (https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_003704035.1/). 
Regarding the parameters, I just tried with the default settings (I am using Smash++ 21.12).

**Comment by pratas** [comment]
Hi, 

but, please, provide me the IDs of two identical chromosomes.
For example, the IDs of chromosome 14 for both (or other).
Then, I will run a optimization.

Best regards,
Diogo

**Comment by lassancejm** [comment]
Sorry, I misunderstood what you meant. 
14 in Mus is chr9 in Peromuscys. X in Mus is chrX in Peromyscus, and this pair would be a good example, since I know there are numerous intrachromosomal rearrangements
Thanks!

**Comment by pratas** [comment]
Thank you for your interest in the tool and by your patience.
Here you have:

1st -> please install the following tools:

conda install -c bioconda smashpp -y
conda install -c bioconda entrez-direct -y
conda install -c cobilab gto -y

2nd -> download the sequences and filter them:

efetch -id NC_056031.1 -format FASTA -db nucleotide | gto_fasta_rand_extra_chars  > CX-PMB.fa
efetch -id NC_000086.7 -format FASTA -db nucleotide | gto_fasta_rand_extra_chars > CX-MM.fa

3rd -> run smashpp with the following parameters (it will take +\- 1 day with 1 core, because it has extreme sensitivity):

smashpp -v -nr -ft 0 -rm 16,0,0.1,0.95/7,0,0.1,0.95 -f 50000 -d 1 -m 800 -th 1.5 -r CX-MM.fa -t CX-PMB.fa
smashpp -viz -nrr -nr -m 800 -o CX-MM.fa.CX-PMB.svg CX-MM.fa.CX-PMB.fa.pos

The minimal contiguous block to be accepted is 800, which can be decrease (although I don't think it will bring much more regions).
I hope it helps.

Best regards,
Diogo

**Comment by Karimi-81** [comment]
Hi there,
I would like to find the re-arrangement between two large chromosome-level genome assmeblies.  I used the above suggested parameters but there is no results (just 1 segmet recognized):
./smashpp/smashpp  -n 30 -v -nr -ft 0 -rm 16,0,0.1,0.95/7,0,0.1,0.95 -f 50000 -d 1 -m 800 -th 1.5 -r dog.fa -t cat.fa

The dog genome is "ROS_Cfam_1.0" and cat is "F.catus_Fca126_mat1.0" downlosed from NCBI. Can you please help me set reigh parameter for this analysis.
Thanks
